# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10helloworld.proto\"\x0f\n\x02M1\x12\t\n\x01\x61\x18\x01 \x01(\x05\"\xb4\x02\n\x02M2\x12\x10\n\x08\x66_double\x18\x01 \x01(\x01\x12\x0f\n\x07\x66_float\x18\x02 \x01(\x02\x12\x0f\n\x07\x66_int32\x18\x03 \x01(\x05\x12\t\n\x01\x64\x18\x04 \x01(\x03\x12\t\n\x01\x65\x18\x05 \x01(\r\x12\t\n\x01\x66\x18\x06 \x01(\x04\x12\x10\n\x08\x66_sint32\x18\x07 \x01(\x11\x12\x10\n\x08\x66_sint64\x18\x08 \x01(\x12\x12\x11\n\tf_fixed32\x18\t \x01(\x07\x12\x11\n\tf_fixed64\x18\n \x01(\x06\x12\x12\n\nf_sfixed32\x18\x0b \x01(\x0f\x12\x12\n\nf_sfixed64\x18\x0c \x01(\x10\x12\x0e\n\x06\x66_bool\x18\r \x01(\x08\x12\x10\n\x08\x66_string\x18\x0e \x01(\t\x12\x0f\n\x07\x66_bytes\x18\x0f \x01(\x0c\x12\x18\n\x10\x66_repeated_int32\x18\x10 \x03(\x05\x12\x1a\n\rf_repeated_m1\x18\x11 \x03(\x0b\x32\x03.M1\"D\n\x0cMessRepeated\x12\x18\n\x10\x66_repeated_int32\x18\x01 \x03(\x05\x12\x1a\n\rf_repeated_m1\x18\x02 \x03(\x0b\x32\x03.M1b\x06proto3')
)




_M1 = _descriptor.Descriptor(
  name='M1',
  full_name='M1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='M1.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=35,
)


_M2 = _descriptor.Descriptor(
  name='M2',
  full_name='M2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f_double', full_name='M2.f_double', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_float', full_name='M2.f_float', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_int32', full_name='M2.f_int32', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d', full_name='M2.d', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e', full_name='M2.e', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f', full_name='M2.f', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_sint32', full_name='M2.f_sint32', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_sint64', full_name='M2.f_sint64', index=7,
      number=8, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_fixed32', full_name='M2.f_fixed32', index=8,
      number=9, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_fixed64', full_name='M2.f_fixed64', index=9,
      number=10, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_sfixed32', full_name='M2.f_sfixed32', index=10,
      number=11, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_sfixed64', full_name='M2.f_sfixed64', index=11,
      number=12, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_bool', full_name='M2.f_bool', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_string', full_name='M2.f_string', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_bytes', full_name='M2.f_bytes', index=14,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_repeated_int32', full_name='M2.f_repeated_int32', index=15,
      number=16, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_repeated_m1', full_name='M2.f_repeated_m1', index=16,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=346,
)


_MESSREPEATED = _descriptor.Descriptor(
  name='MessRepeated',
  full_name='MessRepeated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f_repeated_int32', full_name='MessRepeated.f_repeated_int32', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_repeated_m1', full_name='MessRepeated.f_repeated_m1', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=416,
)

_M2.fields_by_name['f_repeated_m1'].message_type = _M1
_MESSREPEATED.fields_by_name['f_repeated_m1'].message_type = _M1
DESCRIPTOR.message_types_by_name['M1'] = _M1
DESCRIPTOR.message_types_by_name['M2'] = _M2
DESCRIPTOR.message_types_by_name['MessRepeated'] = _MESSREPEATED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

M1 = _reflection.GeneratedProtocolMessageType('M1', (_message.Message,), dict(
  DESCRIPTOR = _M1,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:M1)
  ))
_sym_db.RegisterMessage(M1)

M2 = _reflection.GeneratedProtocolMessageType('M2', (_message.Message,), dict(
  DESCRIPTOR = _M2,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:M2)
  ))
_sym_db.RegisterMessage(M2)

MessRepeated = _reflection.GeneratedProtocolMessageType('MessRepeated', (_message.Message,), dict(
  DESCRIPTOR = _MESSREPEATED,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:MessRepeated)
  ))
_sym_db.RegisterMessage(MessRepeated)


# @@protoc_insertion_point(module_scope)
